apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb-deploy
    namespace: mongodb
spec:
    replicas: 1
    selector:
       matchLabels:
          app: mongodb
    template:
       metadata:
          labels:
             app: mongodb
       spec:
          containers:
           - name: mongodb
             image: mongo:5.0
             imagePullPolicy: "IfNotPresent"
             args: ["--dbpath","/data/db"]
             ports:
               - containerPort: 27017                                   
             volumeMounts:
               - mountPath: "/data/db"
                 name: "mongodb-pv"
          volumes:
            - name: "mongodb-pv"
              persistentVolumeClaim:
                 claimName: mongodb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: mongodb-pv-volume
    namespace: mongodb
    labels:
       type: local
       app: mongodb
spec:
    storageClassName: microk8s-hostpath
    capacity:
       storage: 5Gi
    accessModes:
       - ReadWriteMany
    hostPath:
       path: /data/mongo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: mongodb-pv-claim
    namespace: mongodb
    labels:
       app: mongodb
spec:
    storageClassName: microk8s-hostpath
    accessModes:
       - ReadWriteMany
    resources:
       requests:
          storage: 5Gi
